write_config <- function(
  project_name,
  project_location,
  monitoring_year,
  valid_strata,
  gee_project      = "",
  covariate_raster = "",
  aoi_file         = NULL,
  stratum_field    = NULL,
  output_path      = "soil_carbon_config.R"
) {
  strata_str <- paste0('c(', paste0('"', trimws(valid_strata), '"', collapse = ', '), ')')

  palette <- c("#2d6a4f", "#95d5b2", "#f4a261", "#3399FF", "#FF9999",
               "#CC99FF", "#FFCC99", "#99CCFF", "#FF99CC", "#CCFF99")
  palette <- rep(palette, length.out = length(valid_strata))
  color_entries <- paste(sprintf('  "%s" = "%s"', valid_strata, palette), collapse = ",\n")
  colors_str <- paste0("c(\n", color_entries, "\n)")

  # Default BD values by common stratum code
  bd_lookup <- c(F = 0.90, GL = 1.20, CL = 1.30, PL = 0.15, SL = 1.10,
                 WL = 0.80, Forest = 0.90, Grassland = 1.20, Cropland = 1.30,
                 # Restoration-age classes (bulk density declines with age)
                 `0_5` = 1.30, `5_10` = 1.20, `10_15` = 1.12, `15_20` = 1.05,
                 Remnant = 0.95)
  bd_entries <- paste(vapply(valid_strata, function(s) {
    default_val <- if (s %in% names(bd_lookup)) bd_lookup[[s]] else 1.0
    sprintf('  "%s" = %.2f', s, default_val)
  }, character(1)), collapse = ",\n")
  bd_str <- paste0("list(\n", bd_entries, "\n)")

  gee_line <- if (nchar(trimws(gee_project)) == 0) {
    'GEE_PROJECT <- ""  # Set this before running Pipelines 2, 3, or 4'
  } else {
    paste0('GEE_PROJECT <- "', trimws(gee_project), '"')
  }

  covar_line <- if (nchar(trimws(covariate_raster)) == 0) {
    'COVARIATE_RASTER <- ""  # Path to your GEE covariate raster (28-band TerrestrialSOC export)'
  } else {
    paste0('COVARIATE_RASTER <- "', trimws(covariate_raster), '"')
  }

  aoi_line <- if (is.null(aoi_file) || nchar(trimws(aoi_file)) == 0) {
    'AOI_FILE <- NULL'
  } else {
    paste0('AOI_FILE <- "', trimws(aoi_file), '"')
  }

  stratum_field_line <- if (is.null(stratum_field) || nchar(trimws(stratum_field)) == 0) {
    'AOI_STRATUM_FIELD <- NULL  # column in AOI_FILE identifying strata'
  } else {
    paste0('AOI_STRATUM_FIELD <- "', trimws(stratum_field), '"')
  }

  lines <- c(
    "# ============================================================================",
    "# TERRESTRIAL SOIL CARBON PROJECT CONFIGURATION",
    paste0("# Generated by the Soil Carbon Setup App on ", Sys.Date()),
    "# ============================================================================",
    "",
    "# ── Project metadata ────────────────────────────────────────────",
    paste0('PROJECT_NAME     <- "', project_name, '"'),
    'PROJECT_SCENARIO <- "PROJECT"   # BASELINE | PROJECT | CONTROL | DEGRADED',
    paste0('MONITORING_YEAR  <- ', as.integer(monitoring_year)),
    paste0('PROJECT_LOCATION <- "', project_location, '"'),
    "",
    "# ── Google Earth Engine ───────────────────────────────────────────",
    gee_line,
    "",
    "# ── Input file paths ─────────────────────────────────────────────",
    'PRE_ANALYSIS_DIR <- "Pre-Analysis Data Preparation"',
    'DATA_RAW_DIR     <- file.path(PRE_ANALYSIS_DIR, "data_raw")',
    'DATA_GLOBAL_DIR  <- file.path(PRE_ANALYSIS_DIR, "data_global")',
    'COVARIATES_DIR   <- file.path(PRE_ANALYSIS_DIR, "covariates")',
    "",
    covar_line,
    "",
    aoi_line,
    stratum_field_line,
    "",
    "# ── Land-use strata ──────────────────────────────────────────────",
    "# Must match the `stratum` column in core_locations.csv (and any AOI stratum field).",
    "# Codes are user-defined: e.g. land-use (F, GL, CL) or restoration-age (0_5 ... Remnant).",
    paste0("VALID_STRATA <- ", strata_str),
    "",
    paste0("STRATUM_COLORS <- ", colors_str),
    "",
    "# ── Standard depth intervals ─────────────────────────────────────",
    "# 4-depth scheme: sums to 0-30 cm (topsoil) and 0-100 cm (full profile).",
    "DEPTH_MIDPOINTS <- c(7.5, 22.5, 45, 80)",
    "",
    "DEPTH_INTERVALS <- data.frame(",
    "  depth_top      = c( 0, 15, 30,  60),",
    "  depth_bottom   = c(15, 30, 60, 100),",
    "  depth_midpoint = c(7.5, 22.5, 45, 80),",
    "  thickness_cm   = c(15, 15, 30, 40)",
    ")",
    "",
    "# ── Bulk density defaults ─────────────────────────────────────────",
    "# Applied where bulk_density_g_cm3 is missing (g/cm³).",
    paste0("BD_DEFAULTS <- ", bd_str),
    "",
    "# ── QC thresholds ───────────────────────────────────────────────",
    "QC_SOC_MIN <- 0",
    "QC_SOC_MAX <- 600   # raise to ~900 for peatland-dominated sites",
    "QC_BD_MIN  <- 0.05  # allow low values for organic horizons",
    "QC_BD_MAX  <- 2.0",
    "",
    "# ── Remote sensing band labels ────────────────────────────────────",
    "# 28-band terrestrial canonical stack (see R/preanalysis/gee_covariates.R).",
    "BAND_LABELS <- c(",
    '  "elevation_m"  = "Elevation (m) — drainage, temperature lapse ★",',
    '  "slope"        = "Slope (°) — erosion, drainage ★",',
    '  "aspect"       = "Aspect (°) — solar radiation",',
    '  "twi"          = "TWI — topographic wetness ★",',
    '  "tpi"          = "TPI — topographic position",',
    '  "curvature"    = "Curvature — flow convergence",',
    '  "VV_mean"      = "SAR VV — soil moisture & roughness ★",',
    '  "VH_mean"      = "SAR VH — vegetation volume ★",',
    '  "VVVH_ratio"   = "SAR VV/VH — canopy vs. bare soil",',
    '  "NIR"          = "S2 NIR — vegetation biomass ★",',
    '  "SWIR1"        = "S2 SWIR-1 — soil moisture ★",',
    '  "SWIR2"        = "S2 SWIR-2 — organic matter ★",',
    '  "NDVI_median"  = "NDVI — vegetation density ★",',
    '  "EVI_median"   = "EVI — canopy structure ★",',
    '  "LSWI_median"  = "LSWI — land surface water",',
    '  "SAVI_median"  = "SAVI — soil-adjusted vegetation",',
    '  "NDMI_median"  = "NDMI — moisture stress ★",',
    '  "BSI_median"   = "BSI — bare soil index ★",',
    '  "MAT_C"        = "MAT — mean annual temperature ★",',
    '  "MAP_mm"       = "MAP — mean annual precipitation ★",',
    '  "PET_mm"       = "PET — potential evapotranspiration ★",',
    '  "aridity_index"= "Aridity index (MAP/PET) ★"',
    ")"
  )

  writeLines(lines, output_path)
  invisible(output_path)
}
